// Auto-generated from scraping https://www.talcompany.sk/subpages/projects/
export type Project = {
  id: string;
  title: string;
  year: string;
  category: string;
  image: string;
  galleryImages: string[];
};

export const CATEGORIES = [
  "Všetko",
  "Školy & Nemocnice",
  "Bytové & Rodinné domy",
  "Priemyselné & Inžinierske stavby",
  "Záhrady & Spevnené plochy",
] as const;

export const PROJECTS: Project[] = [
  {
    id: "1",
    title: "Záhradná a krajinná architektúra",
    year: "od roku 2006",
    category: "Záhrady & Spevnené plochy",
    image: "/sources/portfolio/1/harmonia_003.jpg",
    galleryImages: [
      "/sources/portfolio/1/harmonia_003.jpg",
      "/sources/portfolio/1/kramare_002.jpg",
      "/sources/portfolio/1/kramare_004.jpg",
      "/sources/portfolio/1/kramare_011.jpg",
      "/sources/portfolio/1/lozorno_001.jpg",
      "/sources/portfolio/1/lozorno_003.jpg",
      "/sources/portfolio/1/lozorno_005.jpg",
      "/sources/portfolio/1/lozorno_006.jpg",
      "/sources/portfolio/1/marianka_002.jpg",
      "/sources/portfolio/1/marianka_003.jpg",
      "/sources/portfolio/1/marianka_012.jpg",
      "/sources/portfolio/1/marianka_014.jpg",
      "/sources/portfolio/1/marianka_015.jpg",
      "/sources/portfolio/1/marianka_016.jpg",
      "/sources/portfolio/1/muska_002.jpg",
      "/sources/portfolio/1/muska_004.jpg",
      "/sources/portfolio/1/muska_006.jpg",
      "/sources/portfolio/1/muska_008.jpg",
      "/sources/portfolio/1/rajteplice_001.jpg",
      "/sources/portfolio/1/rajteplice_004.jpg",
      "/sources/portfolio/1/rd_bratislava_002.jpg",
      "/sources/portfolio/1/rd_bratislava_003.jpg",
      "/sources/portfolio/1/rd_bratislava_013.jpg",
      "/sources/portfolio/1/rd_bratislava_017.jpg",
      "/sources/portfolio/1/rusovce_002.jpg",
      "/sources/portfolio/1/rusovce_007.jpg",
      "/sources/portfolio/1/rusovce_012.jpg",
      "/sources/portfolio/1/rusovce_017.jpg",
    ],
  },
  {
    id: "2",
    title: "Polyfunkčný objekt na ul. Pivovarská, Žilina",
    year: "rok 2006",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/2/po_pivovarska_001.jpg",
    galleryImages: [
      "/sources/portfolio/2/po_pivovarska_001.jpg",
      "/sources/portfolio/2/po_pivovarska_002.jpg",
    ],
  },
  {
    id: "3",
    title: "Obytný súbor Amfiteáter-Žilina",
    year: "rok 2007",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/3/os_amfiteater_001.jpg",
    galleryImages: [
      "/sources/portfolio/3/os_amfiteater_001.jpg",
      "/sources/portfolio/3/os_amfiteater_002.jpg",
      "/sources/portfolio/3/os_amfiteater_003.jpg",
      "/sources/portfolio/3/os_amfiteater_004.jpg",
      "/sources/portfolio/3/os_amfiteater_005.jpg",
      "/sources/portfolio/3/os_amfiteater_006.jpg",
      "/sources/portfolio/3/os_amfiteater_007.jpg",
      "/sources/portfolio/3/os_amfiteater_008.jpg",
      "/sources/portfolio/3/os_amfiteater_009.jpg",
      "/sources/portfolio/3/os_amfiteater_010.jpg",
      "/sources/portfolio/3/os_amfiteater_011.jpg",
    ],
  },
  {
    id: "4",
    title: "Spol. Softel, Žilina",
    year: "rok 2007",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/4/softel_001.jpg",
    galleryImages: [
      "/sources/portfolio/4/softel_001.jpg",
      "/sources/portfolio/4/softel_002.jpg",
    ],
  },
  {
    id: "5",
    title: "VÚC Žilina",
    year: "rok 2007",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/5/vuc_za_001.jpg",
    galleryImages: [
      "/sources/portfolio/5/vuc_za_001.jpg",
      "/sources/portfolio/5/vuc_za_002.jpg",
    ],
  },
  {
    id: "6",
    title: "SOU Hlinská, Žilina",
    year: "rok 2008",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/6/sou_hlinska_001.jpg",
    galleryImages: [
      "/sources/portfolio/6/sou_hlinska_001.jpg",
      "/sources/portfolio/6/sou_hlinska_002.jpg",
      "/sources/portfolio/6/sou_hlinska_003.jpg",
      "/sources/portfolio/6/sou_hlinska_004.jpg",
      "/sources/portfolio/6/sou_hlinska_005.jpg",
      "/sources/portfolio/6/sou_hlinska_006.jpg",
      "/sources/portfolio/6/sou_hlinska_007.jpg",
      "/sources/portfolio/6/sou_hlinska_008.jpg",
      "/sources/portfolio/6/sou_hlinska_009.jpg",
      "/sources/portfolio/6/sou_hlinska_010.jpg",
      "/sources/portfolio/6/sou_hlinska_011.jpg",
      "/sources/portfolio/6/sou_hlinska_012.jpg",
      "/sources/portfolio/6/sou_hlinska_013.jpg",
      "/sources/portfolio/6/sou_hlinska_014.jpg",
    ],
  },
  {
    id: "7",
    title: "Základná škola v Zázrivej",
    year: "rok 2008",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/7/zs_zazriva_001.jpg",
    galleryImages: [
      "/sources/portfolio/7/zs_zazriva_001.jpg",
      "/sources/portfolio/7/zs_zazriva_003.jpg",
      "/sources/portfolio/7/zs_zazriva_004.jpg",
      "/sources/portfolio/7/zs_zazriva_005.jpg",
      "/sources/portfolio/7/zs_zazriva_006.jpg",
      "/sources/portfolio/7/zs_zazriva_007.jpg",
      "/sources/portfolio/7/zs_zazriva_008.jpg",
      "/sources/portfolio/7/zs_zazriva_009.jpg",
    ],
  },
  {
    id: "8",
    title: "Hotel Prédium, Vráble",
    year: "rok 2009",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/8/predium_001.jpg",
    galleryImages: [
      "/sources/portfolio/8/predium_001.jpg",
      "/sources/portfolio/8/predium_002.jpg",
      "/sources/portfolio/8/predium_003.jpg",
      "/sources/portfolio/8/predium_004.jpg",
      "/sources/portfolio/8/predium_005.jpg",
      "/sources/portfolio/8/predium_006.jpg",
      "/sources/portfolio/8/predium_007.jpg",
      "/sources/portfolio/8/predium_008.jpg",
    ],
  },
  {
    id: "9",
    title: "Základná škola v Tvrdošíne",
    year: "rok 2010",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/9/zs_tvrdosin_001.jpg",
    galleryImages: [
      "/sources/portfolio/9/zs_tvrdosin_001.jpg",
      "/sources/portfolio/9/zs_tvrdosin_002.jpg",
      "/sources/portfolio/9/zs_tvrdosin_003.jpg",
      "/sources/portfolio/9/zs_tvrdosin_005.jpg",
      "/sources/portfolio/9/zs_tvrdosin_006.jpg",
      "/sources/portfolio/9/zs_tvrdosin_007.jpg",
      "/sources/portfolio/9/zs_tvrdosin_008.jpg",
      "/sources/portfolio/9/zs_tvrdosin_009.jpg",
    ],
  },
  {
    id: "10",
    title: "Bytový dom v Stráňavoch",
    year: "rok 2010",
    category: "Bytové & Rodinné domy",
    image: "/sources/portfolio/10/bd_stranavy_001.jpg",
    galleryImages: [
      "/sources/portfolio/10/bd_stranavy_001.jpg",
      "/sources/portfolio/10/bd_stranavy_002.jpg",
      "/sources/portfolio/10/bd_stranavy_003.jpg",
      "/sources/portfolio/10/bd_stranavy_004.jpg",
    ],
  },
  {
    id: "11",
    title: "Atómové elektrárne Mochovce",
    year: "rok 2010-2013",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/11/ae_mochovce_001.jpg",
    galleryImages: [
      "/sources/portfolio/11/ae_mochovce_001.jpg",
      "/sources/portfolio/11/ae_mochovce_002.jpg",
      "/sources/portfolio/11/ae_mochovce_003.jpg",
      "/sources/portfolio/11/ae_mochovce_004.jpg",
      "/sources/portfolio/11/ae_mochovce_005.jpg",
      "/sources/portfolio/11/ae_mochovce_006.jpg",
      "/sources/portfolio/11/ae_mochovce_007.jpg",
      "/sources/portfolio/11/ae_mochovce_008.jpg",
      "/sources/portfolio/11/ae_mochovce_009.jpg",
      "/sources/portfolio/11/ae_mochovce_010.jpg",
      "/sources/portfolio/11/ae_mochovce_011.jpg",
      "/sources/portfolio/11/ae_mochovce_012.jpg",
      "/sources/portfolio/11/ae_mochovce_014.jpg",
      "/sources/portfolio/11/ae_mochovce_015.jpg",
      "/sources/portfolio/11/ae_mochovce_016.jpg",
      "/sources/portfolio/11/ae_mochovce_017.jpg",
      "/sources/portfolio/11/ae_mochovce_018.jpg",
      "/sources/portfolio/11/ae_mochovce_019.jpg",
      "/sources/portfolio/11/ae_mochovce_020.jpg",
    ],
  },
  {
    id: "12",
    title: "Rodinný dom, Do Medzilužia, Žilina",
    year: "rok 2011",
    category: "Bytové & Rodinné domy",
    image: "/sources/portfolio/12/rd_domedziluzia_002.jpg",
    galleryImages: [
      "/sources/portfolio/12/rd_domedziluzia_002.jpg",
      "/sources/portfolio/12/rd_domedziluzia_003.jpg",
      "/sources/portfolio/12/rd_domedziluzia_004.jpg",
      "/sources/portfolio/12/rd_domedziluzia_005.jpg",
      "/sources/portfolio/12/rd_domedziluzia_006.jpg",
      "/sources/portfolio/12/rd_domedziluzia_007.jpg",
      "/sources/portfolio/12/rd_domedziluzia_008.jpg",
      "/sources/portfolio/12/rd_domedziluzia_009.jpg",
    ],
  },
  {
    id: "13",
    title: "Bytový dom, Žilina",
    year: "rok 2011",
    category: "Bytové & Rodinné domy",
    image: "/sources/portfolio/13/bd_bratislavska_001.jpg",
    galleryImages: [
      "/sources/portfolio/13/bd_bratislavska_001.jpg",
      "/sources/portfolio/13/bd_bratislavska_002.jpg",
      "/sources/portfolio/13/bd_bratislavska_003.jpg",
      "/sources/portfolio/13/bd_bratislavska_004.jpg",
    ],
  },
  {
    id: "14",
    title: "Železničný tunel Votice",
    year: "rok 2011",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/14/tunel_votice_001.jpg",
    galleryImages: [
      "/sources/portfolio/14/tunel_votice_001.jpg",
      "/sources/portfolio/14/tunel_votice_002.jpg",
      "/sources/portfolio/14/tunel_votice_003.jpg",
      "/sources/portfolio/14/tunel_votice_004.jpg",
      "/sources/portfolio/14/tunel_votice_005.jpg",
      "/sources/portfolio/14/tunel_votice_006.jpg",
      "/sources/portfolio/14/tunel_votice_007.jpg",
      "/sources/portfolio/14/tunel_votice_008.jpg",
      "/sources/portfolio/14/tunel_votice_009.jpg",
      "/sources/portfolio/14/tunel_votice_010.jpg",
      "/sources/portfolio/14/tunel_votice_011.jpg",
      "/sources/portfolio/14/tunel_votice_012.jpg",
    ],
  },
  {
    id: "15",
    title: "Základná škola Kuncová, Praha 5",
    year: "rok 2011",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/15/zs_kuncova_001.jpg",
    galleryImages: [
      "/sources/portfolio/15/zs_kuncova_001.jpg",
      "/sources/portfolio/15/zs_kuncova_002.jpg",
      "/sources/portfolio/15/zs_kuncova_003.jpg",
      "/sources/portfolio/15/zs_kuncova_004 (1).jpg",
      "/sources/portfolio/15/zs_kuncova_005.jpg",
      "/sources/portfolio/15/zs_kuncova_006.jpg",
      "/sources/portfolio/15/zs_kuncova_007.jpg",
    ],
  },
  {
    id: "16",
    title: "Základná škola, Chlupova, Praha 5",
    year: "rok 2011",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/16/zs_chlupova_001.jpg",
    galleryImages: [
      "/sources/portfolio/16/zs_chlupova_001.jpg",
      "/sources/portfolio/16/zs_chlupova_002.jpg",
      "/sources/portfolio/16/zs_chlupova_003.jpg",
      "/sources/portfolio/16/zs_chlupova_004.jpg",
      "/sources/portfolio/16/zs_chlupova_005.jpg",
      "/sources/portfolio/16/zs_chlupova_006.jpg",
    ],
  },
  {
    id: "17",
    title: "Budova ALPHA, BB Centrum, Praha 4",
    year: "rok 2011-2012",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/17/alpha_praha_001.jpg",
    galleryImages: [
      "/sources/portfolio/17/alpha_praha_001.jpg",
      "/sources/portfolio/17/alpha_praha_002.jpg",
      "/sources/portfolio/17/alpha_praha_003.jpg",
      "/sources/portfolio/17/alpha_praha_004.jpg",
      "/sources/portfolio/17/alpha_praha_005.jpg",
      "/sources/portfolio/17/alpha_praha_006.jpg",
      "/sources/portfolio/17/alpha_praha_007.jpg",
      "/sources/portfolio/17/alpha_praha_008.jpg",
      "/sources/portfolio/17/alpha_praha_009.jpg",
      "/sources/portfolio/17/alpha_praha_010.jpg",
      "/sources/portfolio/17/alpha_praha_011.jpg",
      "/sources/portfolio/17/alpha_praha_012.jpg",
      "/sources/portfolio/17/alpha_praha_013.jpg",
      "/sources/portfolio/17/alpha_praha_014.jpg",
      "/sources/portfolio/17/alpha_praha_015.jpg",
    ],
  },
  {
    id: "18",
    title: "Libenský pivovar, Praha",
    year: "rok 2012",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/18/libereckypivovar_001.jpg",
    galleryImages: [
      "/sources/portfolio/18/libereckypivovar_001.jpg",
      "/sources/portfolio/18/libereckypivovar_002.jpg",
      "/sources/portfolio/18/libereckypivovar_003.jpg",
      "/sources/portfolio/18/libereckypivovar_004.jpg",
      "/sources/portfolio/18/libereckypivovar_005.jpg",
      "/sources/portfolio/18/libereckypivovar_006.jpg",
    ],
  },
  {
    id: "19",
    title: "RD p. Kočiš, Žilina-Budatín",
    year: "rok 2012",
    category: "Bytové & Rodinné domy",
    image: "/sources/portfolio/19/rd_budatin_001.jpg",
    galleryImages: [
      "/sources/portfolio/19/rd_budatin_001.jpg",
      "/sources/portfolio/19/rd_budatin_002.jpg",
    ],
  },
  {
    id: "20",
    title: "Bytový dom v Žiline, ul. Nanterská",
    year: "rok 2012",
    category: "Bytové & Rodinné domy",
    image: "/sources/portfolio/20/nanterska_001.jpg",
    galleryImages: [
      "/sources/portfolio/20/nanterska_001.jpg",
      "/sources/portfolio/20/nanterska_002.jpg",
      "/sources/portfolio/20/nanterska_003.jpg",
      "/sources/portfolio/20/nanterska_004.jpg",
    ],
  },
  {
    id: "21",
    title: "Objekty spol. Schiedel v Trenčíne",
    year: "rok 2014, 2015",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/21/schiedel_001.jpg",
    galleryImages: [
      "/sources/portfolio/21/schiedel_001.jpg",
      "/sources/portfolio/21/schiedel_002.jpg",
      "/sources/portfolio/21/schiedel_003.jpg",
      "/sources/portfolio/21/schiedel_004.jpg",
      "/sources/portfolio/21/schiedel_005.jpg",
      "/sources/portfolio/21/schiedel_006.jpg",
    ],
  },
  {
    id: "22",
    title: "Rodinný dom vo Varíne",
    year: "rok 2014",
    category: "Bytové & Rodinné domy",
    image: "/sources/portfolio/22/rd_varin_001.jpg",
    galleryImages: [
      "/sources/portfolio/22/rd_varin_001.jpg",
      "/sources/portfolio/22/rd_varin_002.jpg",
      "/sources/portfolio/22/rd_varin_003.jpg",
      "/sources/portfolio/22/rd_varin_004.jpg",
      "/sources/portfolio/22/rd_varin_005.jpg",
      "/sources/portfolio/22/rd_varin_006.jpg",
      "/sources/portfolio/22/rd_varin_007.jpg",
      "/sources/portfolio/22/rd_varin_008.jpg",
      "/sources/portfolio/22/rd_varin_009.jpg",
      "/sources/portfolio/22/rd_varin_010.jpg",
    ],
  },
  {
    id: "23",
    title: "Predajňa COOP Jednota v Kamennej Porube",
    year: "rok 2015",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/23/coop_kamporuba_001.jpg",
    galleryImages: [
      "/sources/portfolio/23/coop_kamporuba_001.jpg",
      "/sources/portfolio/23/coop_kamporuba_002.jpg",
      "/sources/portfolio/23/coop_kamporuba_003.jpg",
      "/sources/portfolio/23/coop_kamporuba_004.jpg",
      "/sources/portfolio/23/coop_kamporuba_005.jpg",
      "/sources/portfolio/23/coop_kamporuba_006.jpg",
      "/sources/portfolio/23/coop_kamporuba_007.jpg",
      "/sources/portfolio/23/coop_kamporuba_008.jpg",
      "/sources/portfolio/23/coop_kamporuba_009.jpg",
      "/sources/portfolio/23/coop_kamporuba_010.jpg",
      "/sources/portfolio/23/coop_kamporuba_011.jpg",
      "/sources/portfolio/23/coop_kamporuba_012.jpg",
      "/sources/portfolio/23/coop_kamporuba_013.jpg",
      "/sources/portfolio/23/coop_kamporuba_014 (1).jpg",
      "/sources/portfolio/23/coop_kamporuba_014.jpg",
      "/sources/portfolio/23/coop_kamporuba_015.jpg",
      "/sources/portfolio/23/coop_kamporuba_016.jpg",
      "/sources/portfolio/23/coop_kamporuba_017.jpg",
      "/sources/portfolio/23/coop_kamporuba_018.jpg",
      "/sources/portfolio/23/coop_kamporuba_019.jpg",
      "/sources/portfolio/23/coop_kamporuba_020.jpg",
      "/sources/portfolio/23/coop_kamporuba_021.jpg",
      "/sources/portfolio/23/coop_kamporuba_022.jpg",
      "/sources/portfolio/23/coop_kamporuba_023.jpg",
      "/sources/portfolio/23/coop_kamporuba_024.jpg",
    ],
  },
  {
    id: "24",
    title: "Bilingválne gymnázium v Žiline",
    year: "rok 2015",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/24/gbza_001.jpg",
    galleryImages: [
      "/sources/portfolio/24/gbza_001.jpg",
      "/sources/portfolio/24/gbza_002.jpg",
      "/sources/portfolio/24/gbza_003.jpg",
      "/sources/portfolio/24/gbza_005.jpg",
      "/sources/portfolio/24/gbza_006.jpg",
      "/sources/portfolio/24/gbza_007.jpg",
      "/sources/portfolio/24/gbza_008.jpg",
      "/sources/portfolio/24/gbza_009.jpg",
    ],
  },
  {
    id: "25",
    title: "Regulačné stanice SPP v okrese Žilina",
    year: "rok 2015",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/25/rs_spp_001.jpg",
    galleryImages: [
      "/sources/portfolio/25/rs_spp_001.jpg",
      "/sources/portfolio/25/rs_spp_002.jpg",
      "/sources/portfolio/25/rs_spp_003.jpg",
      "/sources/portfolio/25/rs_spp_004.jpg",
      "/sources/portfolio/25/rs_spp_005.jpg",
      "/sources/portfolio/25/rs_spp_006.jpg",
      "/sources/portfolio/25/rs_spp_007.jpg",
    ],
  },
  {
    id: "26",
    title: "Banka VÚB v Žiline",
    year: "rok 2016",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/26/vub_001.jpg",
    galleryImages: [
      "/sources/portfolio/26/vub_001.jpg",
      "/sources/portfolio/26/vub_002.jpg",
      "/sources/portfolio/26/vub_003.jpg",
      "/sources/portfolio/26/vub_004.jpg",
      "/sources/portfolio/26/vub_005.jpg",
      "/sources/portfolio/26/vub_006.jpg",
      "/sources/portfolio/26/vub_007.jpg",
      "/sources/portfolio/26/vub_008.jpg",
      "/sources/portfolio/26/vub_009.jpg",
      "/sources/portfolio/26/vub_010.jpg",
      "/sources/portfolio/26/vub_011.jpg",
      "/sources/portfolio/26/vub_012.jpg",
    ],
  },
  {
    id: "27",
    title: "Materská škola v Zástraní",
    year: "rok 2016",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/27/zs_zastranie_001.jpg",
    galleryImages: [
      "/sources/portfolio/27/zs_zastranie_001.jpg",
      "/sources/portfolio/27/zs_zastranie_002.jpg",
      "/sources/portfolio/27/zs_zastranie_003.jpg",
    ],
  },
  {
    id: "28",
    title: "Stavby nových cestných mostov a nadjazdov",
    year: "stavby",
    category: "Priemyselné & Inžinierske stavby",
    image: "/proj1.png",
    galleryImages: [
      "/proj1.png",
    ],
  },
  {
    id: "29",
    title: "CAPITIS development, s.r.o",
    year: "od roku 2019",
    category: "Priemyselné & Inžinierske stavby",
    image: "/sources/portfolio/29/capitis_(1).jpg",
    galleryImages: [
      "/sources/portfolio/29/capitis_(1).jpg",
      "/sources/portfolio/29/capitis_(10).jpg",
      "/sources/portfolio/29/capitis_(12).jpg",
      "/sources/portfolio/29/capitis_(13).jpg",
      "/sources/portfolio/29/capitis_(3).jpg",
      "/sources/portfolio/29/capitis_(4).jpg",
      "/sources/portfolio/29/capitis_(5).jpg",
      "/sources/portfolio/29/capitis_(6).jpg",
      "/sources/portfolio/29/capitis_(8).jpg",
    ],
  },
  {
    id: "30",
    title: "ÚVN SNP Ružomberok",
    year: "rekonštrukcia",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/30/uvn_ruzomberok_(1).jpg",
    galleryImages: [
      "/sources/portfolio/30/uvn_ruzomberok_(1).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(10).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(11).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(12).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(13).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(14).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(15).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(16).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(17).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(18).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(19).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(2).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(3)-1.jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(4).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(5).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(6).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(7).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(8).jpg",
      "/sources/portfolio/30/uvn_ruzomberok_(9).jpg",
    ],
  },
  {
    id: "31",
    title: "ÚVN SNP poliklinika Trenčín",
    year: "rekonštrukcia",
    category: "Školy & Nemocnice",
    image: "/sources/portfolio/31/poliklinika_trencin_(1).jpg",
    galleryImages: [
      "/sources/portfolio/31/poliklinika_trencin_(1).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(10).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(11).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(12).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(13).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(14).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(2).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(3).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(4).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(5).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(6).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(7).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(8).jpg",
      "/sources/portfolio/31/poliklinika_trencin_(9).jpg",
    ],
  },
];

export function getProject(id: string): Project | undefined {
  return PROJECTS.find((p) => p.id === id);
}
